server:
  port: 33333
  servlet:
    session:
      timeout: 7200

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

springfox:
  documentation:
    swagger:
      v2:
        path: /engine-fire-api
    swagger-ui:
      base-url: /engine-fire-api