spring:
  config:
    active:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

elasticsearch:
  url: 313.co.kr:9200

jira:
  maxResults: 50
  issue:
    fields: fields=project,issuetype,creator,reporter,assignee,labels,priority,status,resolution,resolutiondate,created,updated,worklogs,timespent,summary

arms:
  backend-core:
    url: http://127.0.0.1:31313