spring:
  config:
    active:
      on-profile: live
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

elasticsearch:
  url: es-coordinating:9200

jira:
  maxResults: 50
  issue:
    fields: fields=project,issuetype,creator,reporter,assignee,labels,priority,status,resolution,resolutiondate,created,updated,worklogs,timespent,summary

arms:
  backend-core:
    url: http://backend-core:31313
logging:
  level:
    web: debug
