server:
  port: 33333
  servlet:
    session:
      timeout: 7200

springfox:
  documentation:
    swagger:
      v2:
        path: /engine-fire-api
    swagger-ui:
      base-url: /engine-fire-api

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration
