spring:
  config:
    active:
      on-profile: dev
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: http://localhost:9200 # Elasticsearch 클러스터의 URL
    username: # Elasticsearch에 대한 사용자 이름 (필요한 경우)
    password: # Elasticsearch에 대한 비밀번호 (필요한 경우)
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.ElasticsearchDialect
    hibernate:
      ddl-auto: none  # option type: create, create-drop, update, validate, none
      # create로 하게되면 기존 테이블을 삭제후 다시 생성하게 된다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

elasticsearch:
  url: www.313.co.kr:9200


jira:
  maxResults: 50
  issue:
    fields: fields=project,issuetype,creator,reporter,assignee,labels,priority,status,resolution,resolutiondate,created,worklogs,timespent,summary